name: Sync App

on:
  push:
    branches: main

defaults:
  run:
    working-directory: ./app

env:
  AWS_REGION: ${{ vars.AMAZON_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: configure credential
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AMAZON_DEPLOY_ROLE }}
      - name: install dependency
        run: bun install
      - name: build application
        run: bun run build
      - name: sync application
        run: |
          aws s3 sync ./out s3://${{ vars.AMAZON_BUCKET }} --delete
